import { Geist, Geist_Mono, Sacramento } from "next/font/google";
// import { GoogleFont } from "next/font/google";

import "./globals.css";
// import "leaflet/dist/leaflet.css";
// const sacramento = GoogleFont({
//   family: "Sacramento",
//   subsets: ["latin"],
//   variable: "--font-sacramento",
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sacramento = Sacramento({
  variable: "--font-sacramento",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Our Wedding Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sacramento.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
